services:
  fyp-backend:
    build: ./app
    env_file:
      - .env
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${FASTAPI_HOST}:${FASTAPI_PORT}/api/health > dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    depends_on:
      mongodb:
        condition: service_started

  mongodb:
    image: mongo:7
    container_name: fyp-mongodb
    restart: always
    expose:
      - "27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DB_NAME}
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: